version: '2'

services:
   python:
      image: kaggle/python
      ports:
         - "8888:8888"
      working_dir: /work
      volumes:
         - ./:/work
      command: jupyter notebook --no-browser --ip=0.0.0.0

